import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const data = await fetch("https://pokeapi.co/api/v2/pokemon").then((res) =>
    res.json()
  );
  return {
    props: {
      pokemon: data,
    },
  };
}

const PokemonDisplay = ({ name, url }: { name: string; url: string }) => {
  const [fetchState, setFetchState] = React.useState<
    { type: "loading" } | { type: "fetched"; data: any } | { type: "error" }
  >({ type: "loading" });

  React.useEffect(() => {
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        setFetchState({ type: "fetched", data });
      })
      .catch((err) => {
        setFetchState({ type: "error" });
      });
  }, []);

  React.useEffect(() => {
    const id = url.split("/").reverse()[0];
    fetch(`/api/pokemon/${id}`)
      .then((res) => res.json())
      .then((data) => {
        console.log(`data fetched for ${id}`, data);
      })
      .catch((err) => {
        console.error(err);
      });
  }, []);

  return (
    <div style={{ padding: "8px", border: "1px solid white" }}>
      <div>{name}</div>
      {fetchState.type === "fetched" && (
        <img src={fetchState.data.sprites.front_default} />
      )}
      {fetchState.type === "error" && <div>An Error Occurred</div>}
    </div>
  );
};

export default function Home({ pokemon }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <pre>{JSON.stringify(props, null, 2)}</pre> */}
        {pokemon.results.map((r: { name: string; url: string }) => (
          <PokemonDisplay key={r.url} name={r.name} url={r.url} />
        ))}
      </main>
    </>
  );
}
