import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

const Test = () => {
  return (
    // <Head>
    <Script
      id="test-script"
      src="http://www.espn.com"
      strategy="afterInteractive"
      onLoad={() => console.log("ive loaded!")}
      onError={(e) => {
        console.error("Script failed to load", e);
      }}
    >{`console.log('hi there')`}</Script>
    // </Head>
  );
};

export default function Home() {
  return (
    <>
      <Test></Test>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Hi there</div>
      </main>
    </>
  );
}
